# Generated by Django 2.2.24 on 2024-04-06 09:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default=None, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
