# Generated by Django 2.2.24 on 2024-04-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20240406_2226'),
    ]

    operations = [
        migrations.RenameField('Owner', 'owner', 'name'),
    ]
